### ISSUE TITLE
Working Demo

### ISSUE THREAD

**Issue by impulsecorp** [ben-arnao/StoRM#2]
It would be helpful if also you had a working demo, using a common dataset such as MNIST (which can be loaded from TF datasets at https://www.tensorflow.org/api_docs/python/tf/keras/datasets/mnist/load_data).

**Comment by ben-arnao** [comment]
@impulsecorp thanks for the suggestion! I have added an end to end example `example_tuner.py` that demonstrates some of the functionality of the tuner. Let me know if you find this helpful.

**Comment by impulsecorp** [comment]
Thanks!

**Comment by impulsecorp** [comment]
I am trying to run it in a notebook on Google Colab and I get an error on this line:
from tuner import Tuner

Can you make a demo with it all in one file?

**Comment by ben-arnao** [comment]
> I am trying to run it in a notebook on Google Colab and I get an error on this line:
> from tuner import Tuner
> 
> Can you make a demo with it all in one file?

It's because you need access to the tuner file. If you download the whole project and tuner.py is in the same directory as example_tuner.py you shouldn't have an issue. You can also copy the tuner code into the example script if you want it all in one script runnable by colab for example. Also you will need to either create a directory "C:\TestProject" or change that line to a valid local path.

**Comment by impulsecorp** [comment]
Yes, it works now in one notebook when I combined the tuner file with your demo file., thanks.
